// Package header renders the banner comment placed at the top of every
// generated file. The layout follows protoc-gen-go's convention — a versions
// block and a source line — with the database/schema metadata and a project
// link appended.
package header

import "strings"

// tool is the generator binary name stamped into the banner ("Code generated by
// <tool>"), and project is the credit line. protokit is generator-neutral, so the
// defaults name the framework; each plugin binary overrides them via [SetTool] at
// startup (and a generator's golden test does the same in its TestMain).
var (
	tool    = "protoc-gen-protokit"
	project = "protokit — https://github.com/the-protobuf-project/protokit"
)

// SetTool sets the generator identity for the banner: the binary name (e.g.
// "protoc-gen-orm") and a project credit derived from it (github.com/
// the-protobuf-project/<name-without-protoc-gen->). Plugin binaries call it once
// at startup so every generated file names the tool that produced it.
func SetTool(name string) {
	tool = name
	repo := strings.TrimPrefix(name, "protoc-gen-")
	project = repo + " — https://github.com/the-protobuf-project/" + repo
}

// SetProject overrides the credit line independently of the tool name.
//
// SetTool derives the project URL by stripping "protoc-gen-" from the binary
// name, which is right when a repository is named after its generator and wrong
// otherwise: protoc-gen-http lives in grpc-gateway-rs, so the derived link
// would point at a repository that does not exist. Call this after SetTool.
//
// A line break in credit is collapsed to a space rather than rejected. Render
// prefixes each line of the banner with "//" or "--", so an embedded newline
// would escape the comment and emit an unparseable file; a generator that
// passes one has made a mistake, but failing a build over a credit line is a
// worse outcome than quietly keeping it on one line.
func SetProject(credit string) {
	project = singleLine(credit)
}

// singleLine collapses CR, LF and CRLF to single spaces.
func singleLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.TrimSpace(s)
}

// Tool returns the current generator binary name ("protoc-gen-orm", …). Other
// generated-output renderers (e.g. the docs README banner) read it so they name
// the same tool the file-header banner does, keeping protokit generator-neutral.
func Tool() string { return tool }

// Info is the metadata rendered into one file's banner. Every field is
// optional: the umbrella datasource file, for instance, aggregates schemas and
// has no single source proto, and a generator that emits no SQL at all — an MCP
// or GraphQL plugin — leaves Database and Schema empty and gets no
// database/schema block.
type Info struct {
	PluginVersion string   // generator plugin version (build ldflags)
	ProtocVersion string   // protoc compiler version (CodeGeneratorRequest)
	Source        string   // originating .proto path(s); omitted when empty
	Database      string   // datasource database name; omitted when empty
	SchemaLabel   string   // "schema" or "schemas"; defaults to "schema"
	Schema        string   // schema name, or schemas list for the umbrella file
	Notes         []string // extra context lines, shown before the project line
}

// Render returns the banner with every line prefixed by prefix ("//" for Go,
// Prisma, and TypeScript; "--" for SQL). Blank separators are emitted as the
// bare prefix with no trailing space, matching the protoc-gen-go convention.
func Render(prefix string, in Info) string {
	lines := []string{
		"Code generated by " + tool + ". DO NOT EDIT.",
		"versions:",
		"\t" + tool + " " + orUnknown(in.PluginVersion),
		"\tprotoc " + orUnknown(in.ProtocVersion),
	}
	if in.Source != "" {
		lines = append(lines, "source: "+in.Source)
	}

	// A generator with no datasource behind it — MCP, GraphQL — leaves both
	// empty; emitting the labels then would put two blank metadata lines at the
	// top of every file it produces.
	if in.Database != "" || in.Schema != "" {
		label := in.SchemaLabel
		if label == "" {
			label = "schema"
		}
		lines = append(lines, "", pad("database")+in.Database, pad(label)+in.Schema)
	}

	if len(in.Notes) > 0 {
		lines = append(lines, "")
		lines = append(lines, in.Notes...)
	}
	lines = append(lines, "", project)

	var b strings.Builder
	for i, ln := range lines {
		if i > 0 {
			b.WriteByte('\n')
		}
		if ln == "" {
			b.WriteString(prefix)
		} else {
			b.WriteString(prefix + " " + ln)
		}
	}
	return b.String()
}

// pad right-pads a metadata label so its values align in a column:
// "database: ", "schema:   ", "schemas:  ".
func pad(label string) string {
	const width = 10 // len("database: ")
	s := label + ":"
	if n := width - len(s); n > 0 {
		s += strings.Repeat(" ", n)
	}
	return s
}

// orUnknown substitutes the protoc-gen-go sentinel for a missing version.
func orUnknown(v string) string {
	if v == "" {
		return "(unknown)"
	}
	return v
}
