package header

import (
	"strings"
	"testing"
)

func TestRender(t *testing.T) {
	got := Render("//", Info{
		PluginVersion: "v0.1.0",
		ProtocVersion: "v5.29.0",
		Source:        "bookstore/v1/bookstore.proto",
		Database:      "bookstore_db",
		Schema:        "bookstore_v1",
	})
	want := "// Code generated by protoc-gen-protokit. DO NOT EDIT.\n" +
		"// versions:\n" +
		"// \tprotoc-gen-protokit v0.1.0\n" +
		"// \tprotoc v5.29.0\n" +
		"// source: bookstore/v1/bookstore.proto\n" +
		"//\n" +
		"// database: bookstore_db\n" +
		"// schema:   bookstore_v1\n" +
		"//\n" +
		"// protokit — https://github.com/the-protobuf-project/protokit"
	if got != want {
		t.Errorf("Render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderSQLPrefixUnknownVersionsAndNotes(t *testing.T) {
	// "--" prefix, missing versions render as "(unknown)", no source line, the
	// "schemas" label aligns its value, and Notes appear before the project line.
	got := Render("--", Info{
		Database:    "bookstore_db",
		SchemaLabel: "schemas",
		Schema:      "bookstore_v1, inventory",
		Notes:       []string{"a note."},
	})
	want := "-- Code generated by protoc-gen-protokit. DO NOT EDIT.\n" +
		"-- versions:\n" +
		"-- \tprotoc-gen-protokit (unknown)\n" +
		"-- \tprotoc (unknown)\n" +
		"--\n" +
		"-- database: bookstore_db\n" +
		"-- schemas:  bookstore_v1, inventory\n" +
		"--\n" +
		"-- a note.\n" +
		"--\n" +
		"-- protokit — https://github.com/the-protobuf-project/protokit"
	if got != want {
		t.Errorf("Render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}

// A generator with no datasource behind it — an MCP or GraphQL plugin — leaves
// Database and Schema empty, and must not get two blank metadata lines at the
// top of every file it produces.
func TestRenderOmitsDatabaseBlockWhenUnset(t *testing.T) {
	SetTool("protoc-gen-mcp")
	t.Cleanup(func() { SetTool("protoc-gen-protokit") })

	got := Render("//", Info{
		PluginVersion: "v1.7.1",
		ProtocVersion: "v5.29.3",
		Source:        "todo/v1/todo_service.proto",
	})
	want := "// Code generated by protoc-gen-mcp. DO NOT EDIT.\n" +
		"// versions:\n" +
		"// \tprotoc-gen-mcp v1.7.1\n" +
		"// \tprotoc v5.29.3\n" +
		"// source: todo/v1/todo_service.proto\n" +
		"//\n" +
		"// mcp — https://github.com/the-protobuf-project/mcp"
	if got != want {
		t.Errorf("Render mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}

// Either field alone still produces the block, so a generator that knows only
// its schema does not silently lose it.
func TestRenderKeepsDatabaseBlockWhenPartiallySet(t *testing.T) {
	got := Render("//", Info{Schema: "bookstore_v1"})
	if !strings.Contains(got, "schema:   bookstore_v1") {
		t.Errorf("schema-only Info dropped the block:\n%s", got)
	}
	if !strings.Contains(got, "database: \n") {
		t.Errorf("schema-only Info should still show an empty database label:\n%s", got)
	}
}
